import ellipseCoverUrl from '@/assets/Ellipse.png';
import type { MapPin } from '../types';

export const MOCK_MAP_PINS: MapPin[] = [
  {
    id: 'pin-1',
    lat: 37.5665,
    lng: 126.978,
    title: 'Never Gonna Give You Up',
    artist: 'Rick Astley',
    coverUrl: ellipseCoverUrl,
    nickname: '냥코',
    introduction: '도가니 살리기 위잉잉잉~',
  },
  {
    id: 'pin-2',
    lat: 37.5682,
    lng: 126.9821,
    title: 'Blinding Lights',
    artist: 'The Weeknd',
    coverUrl: ellipseCoverUrl,
    nickname: '한강러버',
    introduction: '야경 보면서 듣기 딱 좋아요',
  },
  {
    id: 'pin-3',
    lat: 37.5648,
    lng: 126.9752,
    title: 'Dynamite',
    artist: 'BTS',
    coverUrl: ellipseCoverUrl,
    nickname: '방탄단',
    introduction: '여기 벤치에서 듣던 노래예요',
  },
  {
    id: 'pin-4',
    lat: 37.5701,
    lng: 126.9768,
    title: 'Shape of You',
    artist: 'Ed Sheeran',
    coverUrl: ellipseCoverUrl,
    nickname: '산책러',
    introduction: '퇴근길 산책 플레이리스트',
  },
  {
    id: 'pin-5',
    lat: 37.5634,
    lng: 126.9815,
    title: 'Levitating',
    artist: 'Dua Lipa',
    coverUrl: ellipseCoverUrl,
    nickname: '댄스머신',
    introduction: '기분 좋아지는 노래 추천',
  },
];
